# pnp is not compatible with tsc (https://stackoverflow.com/questions/69325144/compiling-typescript-with-dependencies-installed-with-yarn)
nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-3.6.1.cjs
