version: '3'

services:
  postgres:
    image: postgres
    hostname: postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - "./.docker/postgres/data:/var/lib/postgresql/data"
    environment:
      POSTGRES_PASSWORD: postgres

  adminer:
    image: adminer
    hostname: adminer
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: 'postgres'
    depends_on:
      - postgres
