version: '3'

services:
  postgres:
    image: postgres
    hostname: postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - "./.docker/postgres/data:/var/lib/postgresql/data"
    environment:
      POSTGRES_USER: sofash
      POSTGRES_PASSWORD: password

# TODO add here preconfigured authorization for adminer
#  https://github.com/TimWolla/docker-adminer/issues/13
  adminer:
    image: adminer
    hostname: adminer
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: 'postgres'
    depends_on:
      - postgres

  redis-stack:
    image: redis/redis-stack
    hostname: redis-stack
    restart: unless-stopped
    ports:
      - "6379:6379"
      - "8001:8001"
    volumes:
      - "./.docker/redis-stack/data:/data"
