name = "sofash"
main = "dist/main.js"
compatibility_date = "2024-11-12"
compatibility_flags = [ "nodejs_compat_v2" ]

no_bundle = true
rules = [
  { type = "Text", globs = ["main.js.map"], fallthrough = true }
]
