name = "sofash"
main = "dist/main.js"
compatibility_date = "2024-11-12"
compatibility_flags = [ "nodejs_compat" ]

no_bundle = true
rules = [
  { type = "Text", globs = ["main.js.map"], fallthrough = true }
]

[[d1_databases]]
binding = "DB"
database_name = "sofash"
database_id = "9d480b50-c9f8-4829-bfac-50019cba32af"
migrations_dir = "drizzle/migrations"
