name: Dependencies check

on:
  schedule:
    - cron: '0 0 1 * *'
  workflow_dispatch:

jobs:
  deps-check:
    name: Dependencies check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node & NPM
        uses: ./.github/actions/setup

      - name: Check for Outdated Packages
        run: npm outdated
