name: Generate Calendar for Rav-Hen

on:
  workflow_dispatch:
    inputs:
      branchName:
        description: 'Rav Hen branch to search cinemas for'
        required: true
        type: choice
        options:
          - givataiim
          - dizengoff
          - "kiryat ono"
      date:
        description: 'Date to search cinemas for formatted as YYYY-MM-DD'
        required: true
        type: string

permissions:
  contents: read
  pages: write
  id-token: write


jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup

      - run: npm run build --workspace @sofash/cli

      - run: node packages/cli/dist/rav-hen/scripts/create-calendar.js -b ${{ inputs.branchName }} -d ${{ inputs.date }}

      - uses: actions/upload-pages-artifact@v3
        with:
          path: './packages/cli/data'

  deploy:
    runs-on: ubuntu-latest
    needs:
      - generate
    steps:
      - uses: actions/deploy-pages@v4
