name: Create Calendar for Rav-Hen

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        type: choice
        default: info
        options:
          - info
          - debug
      branchName:
        description: 'Rav Hen branch to search cinemas for'
        required: true
        type: choice
        options:
          - givataiim
          - dizengoff
          - "kiryat ono"
      date:
        description: 'Date to search cinemas for formatted as YYYY-MM-DD'
        required: true
        type: string

permissions:
  contents: read
  pages: write
  id-token: write

env:
  LOG_LEVEL: ${{ inputs.logLevel }}

jobs:
  create:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup

      - run: npm run build --workspace @sofash/cli

      - run: npm run rav-hen:create --workspace @sofash/cli -- -b ${{ inputs.branchName }} -d ${{ inputs.date }}

      - uses: actions/upload-pages-artifact@v3
        with:
          path: './packages/cli/data'

  deploy:
    runs-on: ubuntu-latest
    needs:
      - create
    steps:
      - uses: actions/deploy-pages@v4
